- hosts: 127.0.0.1
# - hosts: jetstream  # Uncomment this line for use without packer
  remote_user: ubuntu
  become: yes
  vars:
    - configure_nginx: yes

  tasks:
    - name: Read uname
      shell: uname -r
      register: uname_output

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        update_cache: yes
        cache_valid_time: 3600
      with_items:
        - apt-transport-https
        - ca-certificates
        - linux-image-extra-{{ uname_output.stdout }}
        - linux-image-extra-virtual
        - aptitude

    - name: Add Docker repository key
      apt_key:
        id: 58118E89F3A912897C070ADBF76221572C52609D
        keyserver: hkp://ha.pool.sks-keyservers.net:80
        state: present
      register: add_repository_key
      ignore_errors: true

    - name: Add Docker repository and update apt cache
      apt_repository:
        repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
        update_cache: yes
        state: present

    - name: Install docker
      apt: pkg={{ item }}
      with_items:
        - docker-engine

    - name: Upgrade packages
      apt:
        upgrade: yes
        update_cache: no

    - name: Start docker
      service:
        name: docker
        state: started

    - name: Add docker group
      group:
        name: docker
        state: present

    - name: Add user to docker group
      user:
        name: "{{ansible_ssh_user}}"
        groups: docker
        append: yes

    - name: Install nginx
      apt:
        pkg: nginx
      when: configure_nginx

    - name: Place nginx files
      copy:
        src: "files/{{ item.src }}"
        dest: "/etc/nginx/{{ item.dest }}"
      with_items:
        - { src: nginx.conf, dest: nginx.conf }
        - { src: nginx.servers, dest: "sites-enabled/default.servers" }
        - { src: nginx.locations, dest: "sites-enabled/default.locations" }
        - { src: errdoc.html, dest: errdoc.html }
        - { src: gears.gif, dest: gears.gif }
        - { src: cloud.png, dest: cloud.png }
        - { src: favicon.ico, dest: favicon.ico }
      when: configure_nginx
